### ISSUE TITLE
How to change row header column name?

### ISSUE THREAD

**Issue by Magenta94** [revolist/vue-datagrid#11]
As you can see here [https://codesandbox.io/s/festive-morning-0f7fw?file=/src/App.vue](https://codesandbox.io/s/festive-morning-0f7fw?file=/src/App.vue) the first row header column cell takes the name of the first column header. I was expecting it to be empty at first. Anyway, how can I change it? I've tried `columnTemplate` without success.

![image](https://user-images.githubusercontent.com/15924478/110957220-b527c380-834b-11eb-8ed7-df707084829f.png)

Thanks!

**Comment by revolist** [comment]
Hello, @Magenta94 
Currently, there is no way to do so in a version up to 3.0.
It's recommended to use pin column to achieve same functionality, consider it as faster and more convenient way. Row headers were introduced only as minor plugin. But in 3.0.0-beta.9 for revo-grid core this patch already present, will be released in the nearest time.

https://codesandbox.io/s/dark-surf-gmhfm?file=/src/App.vue

**Comment by Magenta94** [comment]
Thanks, but with pin columns then I have to apply CSS to set the same style as the column headers, row headers have it by default. If it is possible in 3.0.0, I'll wait for that.

**Comment by revolist** [comment]
Published update in beta 3.0.0-beta.1, check it here:
https://codesandbox.io/s/elated-neumann-4ty34?file=/src/App.vue
