### ISSUE TITLE
How to use server side with pagination, filter and sorting?

### ISSUE THREAD

**Issue by sujit-baniya** [revolist/vue-datagrid#12]
I tried to use this library in my project. Please suggest me how can I use this for server side with pagination, filter and sorting of data

**Comment by revolist** [comment]
Hello @sujit-baniya,
we don't have a pagination plugin yet but I'll explain the algorithm how you can proceed, it's quite simple but require some customization on your side.

There are 2 variations of pagination: 1st virtual pagination where you don't have numbers at the bottom but you request data per page in virtual scroll and 2nd physical pagination at the bottom with page numbers.

I think you are talking about 2nd.
What you have todo:
- Send to client-side total number of rows: `total`
- Decide how many rows per page you want to see: `visibleCount`
- Break your `dataSource` accordingly and apply these chunks per page `pageNumber`: 
```js
const dataSource = [..,..,..]; // our data source
const visibleCount = 10; // how many rows we show per page
const numberOfPages = Math.ceil(total / visibleCount); // draw your pages
const currentPage = 3; // let's say we are at the page with index = 3
const currentPageFirstItemIndex = currentPage * visibleCount;
const currentDataSource = dataSource.slice(currentPageFirstItemIndex, visibleCount); // current page datasource

// keep grid bind to source updated based on page index
<v-grid :source="currentDataSource"/>
```

**Comment by luisdnodrizat** [comment]
Hi! thank you for vue-datagrid component!
Any progress with this? (Pagination plugin)
