### ISSUE TITLE
How to add new row

### ISSUE THREAD

**Issue by ITM007** [revolist/vue-datagrid#14]
If I want to add a new blank row, how can I do that?

I originally just used this submit function. My column headers are name, date, age.
```
submit() {
      this.rows.push({ date: '12/24/11' });
      console.log(this.rows);
    },
```

I see that the rows array has the new information in it, but the table is not updated. I would like to do the opposite of the delete issue here: [DeleteRow](https://github.com/revolist/vue-datagrid/issues/9)   instead of having a button delete a row, I want a button at the top that adds a new empty row everytime it is clicked. #

**Comment by revolist** [comment]
@ITM007 you have to mutate object, this.rows = [...this.rows];

**Comment by ITM007** [comment]
Thanks for the response. When I add what you recommended it is something like this 
```
addRow() {
      [{ ...this.rows.push({ date: '11/15/2022' }) }];
      console.log(this.rows);
      return this.rows;
    },
```
I see in my console.log that I am increasing the array value

```
10: Object { date: "11/15/2022" }
11: Object { date: "11/15/2022" }
12: Object { date: "11/15/2022" }
13: Object { date: "11/15/2022" }
14: Object { date: "11/15/2022" }
15: Object { date: "11/15/2022" }
length: 16
```
 But the table does not rerender with the correct amount of rows. How do I rerender the table to show the new amount of rows?
​​

**Comment by revolist** [comment]
Hello @ITM007 
I don't see where are you returning rows in your addRow(), I would recommend creating codesandbox sample.
But seems like what you have todo:

addRow() {
  this.rows.push({ date: '11/15/2022' });
  this.rows = [...this.rows];
}

**Comment by ITM007** [comment]
Thank you that worked. I had it messed up. Thank you @revolist

**Comment by revolist** [comment]
@ITM007 very well! happy using!

**Comment by van-huyen** [comment]
Hi @revolist

I'm having the same problem as you ITM007 but haven't solved it yet.
When adding a new row to the grid, the data is added to the source but not displayed on the grid (grid does not refresh)

    func_add_new() {
      this.$refs.vgrid.source.splice(mouse_row, 0, new_row_record)
      this.$refs.vgrid.$el.refresh('all')
      // var items = this.$refs.vgrid.source
      // items.splice(mouse_row, 0, new_row_record)
      // this.$refs.vgrid.source = [...items]
      this.$refs.menu.close()
    },
    
    Thank
