### ISSUE TITLE
nuxt js support

### ISSUE THREAD

**Issue by stickpro** [revolist/vue-datagrid#15]
is it possible to somehow use it together with nuxt js, if yes then you can connect example

**Comment by revolist** [comment]
@stickpro I don't see any reason why you can't, nuxt is just framework based on vue. It is using vuejs components.
To build an example with nuxt will require time, if it get some votes here we surely will.

**Comment by stickpro** [comment]
@revolist ok, may be u can help me. I register component 
![image](https://user-images.githubusercontent.com/25886722/114385251-74180e80-9b98-11eb-8ee4-805c04eff607.png)

import in in nuxt.config.js 
![image](https://user-images.githubusercontent.com/25886722/114385293-86924800-9b98-11eb-83cc-09485ee2e1a0.png)

try use example 
![image](https://user-images.githubusercontent.com/25886722/114385506-ca854d00-9b98-11eb-9e91-d41071f12e6e.png)

end him not render have only one warning 
![image](https://user-images.githubusercontent.com/25886722/114385599-dffa7700-9b98-11eb-9d3d-aae7d2fab4a7.png)

**Comment by stickpro** [comment]
ohhh sry, it's worked need add some height for v-grid

**Comment by revolist** [comment]
@stickpro happy you've solved it.
if any questions/suggestions/ideas arise write us!
