### ISSUE TITLE
How to emit an function in cell template custom in of VGridVueTemplate 

### ISSUE THREAD

**Issue by viralmodern** [revolist/vue-datagrid#17]
Hello @revolist , your product very perfect with many user has been use but i become with an issue at cell child.
VGridVueTemplate(CustomComponent), I do it, and tired emit an event in CustomComponent 
this.$emit('sendToParent') => you can let me know parent component of CustomComponent? I can listen from my parent component has include v-grid, pls, how to use?  
Thanks

**Comment by revolist** [comment]
Hello @viralmodern 
thank you for choosing our component

I would suggest to provide codesandbox sample for faster response.
I would provide some idea how you can solve it and why it has to be this way:

- cell template is using different level of child vue application and you can not catch it with simple $emit and listener on grid.
- what you have to do you have to trigger custom event:
```
const event = new CustomEvent('meEvent', { detail: detail, cancelable: true });
$el.dispatchEvent(event);
```

**Comment by xcchcaptain** [comment]
@viralmodern  just as @revolist 's advice
we could also use EventBus to solve this problem
[example](https://codesandbox.io/s/revogrid-vuecomponent-forked-3izdjy?file=/src/App.vue)
