### ISSUE TITLE
Uncaught (in promise) Error: Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by brian-gerrity** [revolist/vue-datagrid#19]
I have been trying to set up in vue3 and now I am getting this error.  This is the code for the grid page
`<template>`
    `<div>`
        `<!--<ul>`
            `<li v-for="ticket in tickets" :key="ticket.id">`
               ` {{ticket.title}} - ({{ticket.ticket_number}})`
            `</li>`
        `</ul> -->`
        `<h3>Table Start</h3>`
        `<v-grid`
         `   theme="default"`
          `  :source="rows"`
           ` :columns="columns"`
        `></v-grid>`
        `<h3>Table End</h3>`
       ` <pre>{{tickets}}</pre>`
    `</div>`
`</template>`

`<script>`
    import AppLayout from '@/Layouts/NewAppLayout'
    import VGrid from "@revolist/vue3-datagrid";
    
    export default {
        components: {
            AppLayout,
            VGrid
        },

        props: {
            can: Object,
            tickets: Object,
            user: Object,
        },
        data() {
            return {
            columns: [
                { 
                    prop: "ticket_number",
                    name: "Number"
                },
                {
                    prop: "title",
                    name: "Title" 
                },
                {
                    prop: "account_id",
                    name: "Account" 
                }
            ],
            rows: [
        {
          ticket_number: "HD-21021",
          title: "Ut voluptates reiciendis illo tenetur minima.",
          account_id: "4",
        },
        {
          ticket_number: "HD-21156",
          title: "Aut totam aut veniam qui.",
          account_id: "3",
        },
      ],
            // rows: this.tickets
            };
        },

        layout: AppLayout,
    }
`</script>`

`<style>`

revo-grid {
  height: 100%;
}
`</style>`

**Comment by revolist** [comment]
For vue3 you have to use vue3-datagrid, it's another repo.
