### ISSUE TITLE
Grid won't render

### ISSUE THREAD

**Issue by seifkhazna** [revolist/vue-datagrid#20]
After multiple attempts using the example code the grid component won't render at all the following errors are shown in the console: 

`Uncaught TypeError: e is not a function
    ya vgrid.js:1
    React 17
    mountReactComponent vuera.cjs.js:354
    mounted vuera.cjs.js:362
    VueJS 18
    init vue-router.esm.js:2989
    init vue-router.esm.js:2988
    updateRoute vue-router.esm.js:2409
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2397
    step vue-router.esm.js:2001
    step vue-router.esm.js:2005
    iterator vue-router.esm.js:2379
    _callee$ index.js:112
    Babel 10
    iterator vue-router.esm.js:2357
    step vue-router.esm.js:2004
    step vue-router.esm.js:2008
    runQueue vue-router.esm.js:2012
    confirmTransition vue-router.esm.js:2392
    step vue-router.esm.js:2001
    step vue-router.esm.js:2005
    iterator vue-router.esm.js:2379
    resolve vue-router.esm.js:2127
    once vue-router.esm.js:2203
vgrid.js:1
The above error occurred in the <ya> component:

ya@webpack-internal:///./node_modules/@revolist/vue-datagrid/dist/vgrid.js:1:337873
ReactInVue@webpack-internal:///./node_modules/vuera/dist/vuera.cjs.js:299:21

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. react-dom.development.js:20085
[Vue warn]: Error in mounted hook: "TypeError: e is not a function"

found in

---> <ReactWrapper>
       <VGrid>
         <Grid> at src/router/views/dashboards/dgd/testTable.vue
           <Horizontal> at src/router/layouts/horizontal.vue
             <Layout> at src/router/layouts/main.vue
               <Funnel> at src/router/views/dashboards/dgd/index.vue
                 <App> at src/App.vue
                   <Root> vue.runtime.esm.js:619
TypeError: e is not a function
    ya vgrid.js:1
    React 17
    mountReactComponent vuera.cjs.js:354
    mounted vuera.cjs.js:362
    VueJS 18
    init vue-router.esm.js:2989
    init vue-router.esm.js:2988
    updateRoute vue-router.esm.js:2409
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2397
    step vue-router.esm.js:2001
    step vue-router.esm.js:2005
    iterator vue-router.esm.js:2379
    _callee$ index.js:112
    Babel 10
    iterator vue-router.esm.js:2357
    step vue-router.esm.js:2004
    step vue-router.esm.js:2008
    runQueue vue-router.esm.js:2012
    confirmTransition vue-router.esm.js:2392
    step vue-router.esm.js:2001
    step vue-router.esm.js:2005
    iterator vue-router.esm.js:2379
    resolve vue-router.esm.js:2127
    once vue-router.esm.js:2203`

**Comment by revolist** [comment]
Hello @seifkhazna, Not very clear about your environment and setup. Need more information to solve it.
