### ISSUE TITLE
Custom components with vuetify fail

### ISSUE THREAD

**Issue by TBxy** [revolist/vue-datagrid#21]
Hi,

I have some trouble setting up revo-grid with [vuetify](https://vuetifyjs.com/en/) and custom components.
Some elements work fine (eg. `v-switch`), but others do not work at all (eg. `v-icon`).

See an example here:
https://codesandbox.io/s/revo-grid-with-vuetify-2e7ls?file=/src/layout.vue

It seems that the component does not have access to `this.$vuetify`.

**Is there something wrong with my setup?**

I had similiar issues with some [primevue](https://primefaces.org/primevue/) components.

It is also not possible to use vuetify components with the default VNode renderer (third column in the example).

**Error message:**

    [Vue warn]: Error in render: "TypeError: Cannot read property 'component' of undefined" found in ...

Thank you.

**Comment by revolist** [comment]
Hello @TBxy, sorry for the late answer.
The key is every cell is independent Vue component and it has no connection with parent app.
There are several options to solve it, on of the easiest would be to make your own extension for cell wrapper and path Vuetify object to cell component.

In the nearest future we shall solve it.
