### ISSUE TITLE
How to add behavior to set defines the transition animation are smooth on scrollToColumnProp. 

### ISSUE THREAD

**Issue by ducvietsqt** [revolist/vue-datagrid#22]
@revolist  Method scrollToColumnProp in the lib look good but when i try hard make scroll to smooth better, i can't not found properties in API docs, this look like scrollIntoView({behavior: "smooth", block: "end", inline: "nearest"}) in native event of Element Object. Let me know how to implement that solution?. Please, thank you.

**Comment by revolist** [comment]
Hello @ducvietsqt, the easier would be to take work from revogrid and improve it with your request, current version doesn't  this feature, probably we'll make extra plugin for in in the future
