### ISSUE TITLE
Grid does not render

### ISSUE THREAD

**Issue by karladler** [revolist/vue-datagrid#23]
I'm using recent vue-revogrid with Typescript and composition API.
Implementing the basic example the component is not rendering, but I figured the html output looks like this:

```html
<revo-grid grid-uuid="1624448631218-rvgrid" theme="default" row-class="">
  <div class="main-viewport">
    <div class="viewports">
      <revogr-viewport-scroll class="rgCol" grid-uuid="1624448631218-rvgrid-0">
      <!--.... -->
```

I'm not sure what is happening here exactly, but my guess is, that it tries to use web components here. There is probably some step missing in the documentation?

Environment
"vue": "^2.6.11",
"@revolist/vue-datagrid": "^3.0.95",
"typescript": "4",

**Comment by M07amedReda** [comment]
Just add height
`<v-grid style="height : 400px"></v-grid>`

**Comment by revolist** [comment]
You can make height dynamic etc.
But the component has to apply any height.

**Comment by martindemello** [comment]
could you add this to the basic example? i spent a lot of time trying to figure it out too.

**Comment by zaqxs123456** [comment]
@martindemello Agree! I expected it to work right away when I copy the Vue example from official doc.
