### ISSUE TITLE
Refresh method in vue ref is undefined

### ISSUE THREAD

**Issue by Nikitoring** [revolist/vue-datagrid#25]
I'm trying refresh my table. My component has ref, but if I call refresh in function update like this..$refs.table.refresh('all'), refresh is undefined.
If I call table like document.querySelector("revo-grid"), I have refresh method.
Example: https://codesandbox.io/s/revolist-izs09?file=/src/App.vue

**Comment by powerdot** [comment]
Try to get ref element (`this.$refs.vgridref.$el`) and call refresh:
```js
this.$refs.vgridref.$el.refresh("all");
```

**Comment by Nikitoring** [comment]
@powerdot Yes. I have access to refresh method, if  I call it like `$refs.vgtable.$el`

**Comment by datainvestor** [comment]
Could oyu please share working solution? I cant make it work using your codesandbox, as well as in my project.
