### ISSUE TITLE
Emit events not working on Vue3 +3.0.5 versions

### ISSUE THREAD

**Issue by luisdoniad** [revolist/vue-datagrid#27]
Hi! There is a problem trying to handle revogrid events on current vue 3 versions.
I prepared two codesandbox working / not working.

Working on vue 3.0.5 or lower versions:
https://codesandbox.io/s/nd9g2?file=/src/App.vue

Not working on 3.0.6 or newer versions:
https://codesandbox.io/s/o37hj?file=/src/App.vue

Steps to reproduce:
- Click on cell for trigger beforeCellFocus component event or click on column header for trigger beforeSorting component event.
- Then look at to console messages.

Waiting for your response. Thank you so much.

**Comment by exherb** [comment]
@beforesorting works
