### ISSUE TITLE
How to add drag or click to resize column?

### ISSUE THREAD

**Issue by datainvestor** [revolist/vue-datagrid#28]
So based on codesandbox example, how do I add ability to resize columns by draggin (extending them) or to click on the to autoresize?
Here is my codesandbox:
https://codesandbox.io/s/distracted-heisenberg-reexb?file=/src/components/Table.vue

**Comment by zaqxs123456** [comment]
add `resize="true"` in `<v-grid>`:

```
<template>
  <v-grid
    theme="compact"
    resize="true"
    :grouping="grouping"
    :source="rows"
    :columns="columns"
    id="vtable"
  ></v-grid>
</template>
```
