### ISSUE TITLE
Invalid array length error

### ISSUE THREAD

**Issue by bbbford** [revolist/vue-datagrid#3]
After updating to version 2, receive invalid array length error.

Repro:
[https://codesandbox.io/s/revogrid-vueeditor-forked-q5tio](https://codesandbox.io/s/revogrid-vueeditor-forked-q5tio)

![image](https://user-images.githubusercontent.com/5225875/103247469-a163e800-492c-11eb-9ed8-752dc763c565.png)

**Comment by revolist** [comment]
@bbbford ty for quick catch, building an update.

**Comment by revolist** [comment]
Should be fine now.

**Comment by bbbford** [comment]
working, thanks!
