### ISSUE TITLE
Scroll Focus

### ISSUE THREAD

**Issue by jlippold** [revolist/vue-datagrid#33]
When using the arrow keys to navigate the spreadsheet in vue, and you navigate outside of the viewable scroll area, the view doesn't adjust to show the focused cell. But it does work on the demo found here: https://revolist.github.io/revogrid/demo/

Is there a plugin or property that revogrid is using that vue-datagrid is not?

Thanks for the help

**Comment by koendeschacht** [comment]
@jlippold I just submitted a very similar bug  https://github.com/revolist/vue-datagrid/issues/39 . Maybe that's also your problem?

As a temporary fix you can add this styling:
