### ISSUE TITLE
VGridVueTemplate issue on Vue 3

### ISSUE THREAD

**Issue by c4b4d4** [revolist/vue-datagrid#40]
Does VGridVueTemplate work on Vue 2 only? I'm using **Vue 3**, and I see nothing being rendered on the screen.

My column config is as simple as: 
```
import * as Boton from "@/components/Button.vue"
```
```
{
  name:"Edit",
  prop:"edit",
  cellTemplate: VGridVueTemplate(Button, {label:"Edit"})
}
```

But the cell appears **empty**.

I'm even adding a log to see if the component ever gets mounted

```
mounted(){
    console.error("Mounted button",this.label);
}
```

But it does not.

**Comment by marcos-vinicius-dev** [comment]
It does not work for me. Cannot pass custom props. 

https://codesandbox.io/s/revo-grid-vue3-template-cell-forked-tn6npm?file=/src/App.vue
