### ISSUE TITLE
Awkward error in rendering v-grid 

### ISSUE THREAD

**Issue by sanjaybh07** [revolist/vue-datagrid#54]
I am new to Vue JS..I wanted to make use of revo-grid first time, Firstly, I was stucked in the issue of showing no record display in the grid..Now , the issue is changed in an awkward error [vgrid.js?9bbb:1 Uncaught (in promise) TypeError: r is not a function
    at m (vgrid.js?9bbb:1:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:917:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?5c40:5580:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?a1e9:185:1)
    at instance.update (runtime-core.esm-bundler.js?5c40:5694:1)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:5708:1)
    at mountComponent (runtime-core.esm-bundler.js?5c40:5490:1)
    at processComponent (runtime-core.esm-bundler.js?5c40:5448:1)
    at patch (runtime-core.esm-bundler.js?5c40:5038:1)
    at mountChildren (runtime-core.esm-bundler.js?5c40:5234:1)
m @ vgrid.js?9bbb:1
renderComponentRoot @ runtime-core.esm-bundler.js?5c40:917
componentUpdateFn @ runtime-core.esm-bundler.js?5c40:5580
run @ reactivity.esm-bundler.js?a1e9:185
instance.update @ runtime-core.esm-bundler.js?5c40:5694
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5708
mountComponent @ runtime-core.esm-bundler.js?5c40:5490
processComponent @ runtime-core.esm-bundler.js?5c40:5448
patch @ runtime-core.esm-bundler.js?5c40:5038
mountChildren @ runtime-core.esm-bundler.js?5c40:5234
mountElement @ runtime-core.esm-bundler.js?5c40:5143
processElement @ runtime-core.esm-bundler.js?5c40:5115
patch @ runtime-core.esm-bundler.js?5c40:5035
componentUpdateFn @ runtime-core.esm-bundler.js?5c40:5587
run @ reactivity.esm-bundler.js?a1e9:185
instance.update @ runtime-core.esm-bundler.js?5c40:5694
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5708
mountComponent @ runtime-core.esm-bundler.js?5c40:5490
processComponent @ runtime-core.esm-bundler.js?5c40:5448
patch @ runtime-core.esm-bundler.js?5c40:5038
componentUpdateFn @ runtime-core.esm-bundler.js?5c40:5660
run @ reactivity.esm-bundler.js?a1e9:185
instance.update @ runtime-core.esm-bundler.js?5c40:5694
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:155
flushJobs @ runtime-core.esm-bundler.js?5c40:396
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?5c40:285
queueCb @ runtime-core.esm-bundler.js?5c40:307
queuePostFlushCb @ runtime-core.esm-bundler.js?5c40:313
queueEffectWithSuspense @ runtime-core.esm-bundler.js?5c40:1582
scheduler @ runtime-core.esm-bundler.js?5c40:1804
triggerEffect @ reactivity.esm-bundler.js?a1e9:394
triggerEffects @ reactivity.esm-bundler.js?a1e9:384
triggerRefValue @ reactivity.esm-bundler.js?a1e9:1000
eval @ reactivity.esm-bundler.js?a1e9:1131
triggerEffect @ reactivity.esm-bundler.js?a1e9:394
triggerEffects @ reactivity.esm-bundler.js?a1e9:379
triggerRefValue @ reactivity.esm-bundler.js?a1e9:1000
eval @ reactivity.esm-bundler.js?a1e9:1131
triggerEffect @ reactivity.esm-bundler.js?a1e9:394
triggerEffects @ reactivity.esm-bundler.js?a1e9:379
triggerRefValue @ reactivity.esm-bundler.js?a1e9:1000
set value @ reactivity.esm-bundler.js?a1e9:1044
finalizeNavigation @ vue-router.esm-bundler.js?6c02:3214
eval @ vue-router.esm-bundler.js?6c02:3087
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?6c02:3058
push @ vue-router.esm-bundler.js?6c02:2986
install @ vue-router.esm-bundler.js?6c02:3403
use @ runtime-core.esm-bundler.js?5c40:4327
eval @ main.js?56d7:23
./src/main.js @ app.js:1771
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:2228
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997]
[vgrid rendering code.txt](https://github.com/revolist/vue-datagrid/files/8993953/vgrid.rendering.code.txt)

How can anyone work on this if these kind of errors come.. Surprisingly, this issue is coming even with the code provided on GITHub which is running in Sandbox window but it is not running in my code..I did not get a single article on this error on Google also..

**Comment by m2a2x** [comment]
It's better to follow issue template
if still relevant please try to reproduce it with codesanbox from the fresh version 
we'll be able to investigate
