### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by LeonardSpencer** [revolist/vue-datagrid#6]
Hi! Great work on this component. Will try it out the couple of weeks so I think you can aspect more issues-tickets from me with bugs or feature requests :). Is there a definition file present for Typescript?

**Comment by revolist** [comment]
The whole component RevoGrid built with typescript. I ou can have all type definitions from it.

**Comment by seangwright** [comment]
This package is missing the `.d.ts` file that should be generated from the TypeScript compilation

![Screenshot 2021-12-16 132919](https://user-images.githubusercontent.com/1382768/146428296-72791824-a235-4153-80e2-9738d6c75177.jpg)

This screenshot was taken in a Vue 3 (3.2.24) project using v3.0.97 of this library.

**Comment by NathanVG** [comment]
Please re-open, I am not getting TS support with Vue 3. 

<img width="988" alt="Screenshot 2022-04-12 at 00 04 43" src="https://user-images.githubusercontent.com/3620183/162841203-103878b5-4b84-4e47-8e9d-191b1bf76a46.png">

There seems to be an issue in the package itself: 

<img width="919" alt="image" src="https://user-images.githubusercontent.com/3620183/162841342-a7ef183f-eb44-4bc2-9e78-7709fd3c4335.png">
