### ISSUE TITLE
Sorting is broken in 3.6.18

### ISSUE THREAD

**Issue by bbbford** [revolist/vue-datagrid#69]
When clearing the sort in the grid, all data in the grid becomes blank.

Repro steps:

1. Click on a column to sort ascending
2. Click on same column to sort descending
3. Click on same column to clear sort
4. The grid is now blank

<img width="599" alt="image" src="https://github.com/revolist/vue-datagrid/assets/5225875/af74b9fa-b251-4deb-938b-beb6acdf2196">
<img width="593" alt="image" src="https://github.com/revolist/vue-datagrid/assets/5225875/1a17ecf6-40e8-4e63-ade2-59dd10d6de50">
<img width="590" alt="image" src="https://github.com/revolist/vue-datagrid/assets/5225875/bfe6c478-5457-42d3-ae40-a5027905154d">

Code sandbox: https://codesandbox.io/s/patient-fire-23d4ks?file=/src/App.vue

**Comment by revolist** [comment]
Try v4. Should be ok.
