### ISSUE TITLE
Cell content drag & drop

### ISSUE THREAD

**Issue by Icarian2021** [revolist/vue-datagrid#7]
Hi,

Is individual cell to cell drag & drop a feature which is available at the moment?
If yes, is there an example I could use to try and understand?
If not, is this something which will be possible in the near future?

Thanks!

Icarian

**Comment by revolist** [comment]
Hello @Icarian2021,
Please provide us with a sample of what are you talking about, for now, it's not very clear. The same description can mean multiple things.

**Comment by revolist** [comment]
Closed because of inactivity.
