### ISSUE TITLE
Building Error issue

### ISSUE THREAD

**Issue by tech-alpinist** [revolist/vue-datagrid#71]
Hello,
 
Thanks for this great data-grid.
I have issue while building. I am using `@revolist/revogrid-column-date` and `@revolist/revogrid-column-select` for my data-grid.
But, I am getting error and not able to build my project. That seems like node_module issue.
![image](https://github.com/revolist/vue-datagrid/assets/122791147/e10e392e-2e3f-4ed8-9d74-4d62576e7584)

**Comment by akihiro999ina** [comment]
I have the same issue, 

I am looking forward to hearing from you

**Comment by tech-alpinist** [comment]
solved with tsconfig by setting skipLibCheck: false
