### ISSUE TITLE
Column selectplugin not working like the example

### ISSUE THREAD

**Issue by dwaynehulsman** [revolist/vue-datagrid#8]
The column select plugin does not appear to work the way it is supposed to, when clicking on a column it tries to edit the raw value rather then open the selection box.

![image](https://user-images.githubusercontent.com/9630519/108975260-9a382c80-7686-11eb-89cb-ffd586e78207.png)

In the example this did not seem to be the case.

**Comment by dwaynehulsman** [comment]
After some more trial and error, I managed to get a working situation by making the description the same as the key, this is not ideal. Perhaps I'm doing something wrong, I will try supplying a sample later.

**Comment by revolist** [comment]
@dwaynehulsman if you provide a sample it'll explain more.
