### ISSUE TITLE
Deleting a row

### ISSUE THREAD

**Issue by dwaynehulsman** [revolist/vue-datagrid#9]
Is there a way to delete a row from the datagrid? I've tried creating a custom cell with a method modifying the data, however deleting the row only results in cell values being cleared.

**Comment by revolist** [comment]
Hello @dwaynehulsman,
hope this will help you.

https://codesandbox.io/s/revo-grid-delete-row-js-2v06j?file=/src/index.js

For the future, I recommend to provide us with sandboxes you are working on, it'll speedup our answers.

**Comment by kaneda-jp** [comment]
I'm Japanese and I'm not good at English
I'm sorry if you don't understand the question

The delete button of vue component is implemented in each column.
I want to delete a line by pressing a button
Please tell me how to do it.
